export default {
    ADD_PRODUCT_REQUEST:"ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_WENT:"ADD_PRODUCT_WENT",
    ADD_PRODUCT_FAILED:"ADD_PRODUCT_FAILED",

    UPDATE_PRODUCT_REQUEST:"UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_WENT:"UPDATE_PRODUCT_WENT",
    UPDATE_PRODUCT_FAILED:"UPDATE_PRODUCT_FAILED",

    DELETE_PRODUCT_REQUEST:"DELETE_PRODUCT_REQUEST",
    DELETE_PRODUCT_WENT:"DELETE_PRODUCT_WENT",
    DELETE_PRODUCT_FAILED:"DELETE_PRODUCT_FAILED",

    FIND_SELLER_PRODUCTS_REQUEST:"FIND_SELLER_PRODUCTS_REQUEST",
    FIND_SELLER_PRODUCTS_WENT:"FIND_SELLER_PRODUCTS_WENT",
    FIND_SELLER_PRODUCTS_FAILED:"FIND_SELLER_PRODUCTS_FAILED",

    FIND_SELLER_ONE_PRODUCT_REQUEST:"FIND_SELLER_ONE_PRODUCT_REQUEST",
    FIND_SELLER_ONE_PRODUCT_WENT:"FIND_SELLER_ONE_PRODUCT_WENT",
    FIND_SELLER_ONE_PRODUCT_FAILED:"FIND_SELLER_ONE_PRODUCT_FAILED",


}
