export default {
    GET_API_KEY_REQUEST:"GET_API_KEY_REQUEST",
    GET_API_KEY_SUCCESSFUL:"GET_API_KEY_SUCCESSFUL",
    GET_API_KEY_FAILED:"GET_API_KEY_FAILED",

    UPDATE_YOUR_SETTINGS_FAILED: "UPDATE_YOUR_SETTINGS_FAILED",
    UPDATE_YOUR_SETTINGS_WENT: "UPDATE_YOUR_SETTINGS_WENT",
    GET_YOUR_SETTINGS_FAILED: "GET_YOUR_SETTINGS_FAILED",
    GET_YOUR_SETTINGS_WENT: "GET_YOUR_SETTINGS_WENT"

}