export default {
    FIND_STORE_INFORMATION_REQUEST: "FIND_STORE_INFORMATION_REQUEST",
    FIND_STORE_INFORMATION_FAILED: "FIND_STORE_INFORMATION_FAILED",
    FIND_STORE_INFORMATION_WENT: "FIND_STORE_INFORMATION_WENT",

    PROCESS_PURCHASE_INFO_WENT:'PROCESS_PURCHASE_INFO_WENT',
    PROCESS_PURCHASE_INFO_FAILED:'PROCESS_PURCHASE_INFO_FAILED',
    PROCESS_PURCHASE_INFO_REQUEST:'PROCESS_PURCHASE_INFO_REQUEST'
}