export default {
    FIND_STORE_INFORMATION_REQUEST: "FIND_STORE_INFORMATION_REQUEST",
    FIND_STORE_INFORMATION_FAILED: "FIND_STORE_INFORMATION_FAILED",
    FIND_STORE_INFORMATION_WENT: "FIND_STORE_INFORMATION_WENT",

    PROCESS_PURCHASE_INFO_WENT:'PROCESS_PURCHASE_INFO_WENT',
    PROCESS_PURCHASE_INFO_FAILED:'PROCESS_PURCHASE_INFO_FAILED',
    PROCESS_PURCHASE_INFO_REQUEST:'PROCESS_PURCHASE_INFO_REQUEST',

    FIND_TX_HASH_REQUEST: "FIND_TX_HASH_REQUEST",
    FIND_TX_HASH_SUCCESSFUL: 'FIND_TX_HASH_SUCCESSFUL',
    FIND_TX_HASH_FAILED: "FIND_TX_HASH_FAILED",

    ANY_REQUEST_CANCELLATION: "ANY_REQUEST_CANCELLATION",

    STORE_WHAT_TO_SEND: "STORE_WHAT_TO_SEND",
    UPDATE_STEP: "UPDATE_STEP",
    
    FIND_FULL_TX_REQUEST: "FIND_FULL_TX_REQUEST",
    FIND_FULL_TX_SUCCESSFUL: 'FIND_FULL_TX_SUCCESSFUL',
    FIND_FULL_TX_FAILED: "FIND_FULL_TX_FAILED",

    CLEAR: "CLEAR"
}