export default {
    GET_ORDERS_WENT: "GET_ORDERS_WENT",
    GET_ORDERS_FAILED: "GET_ORDERS_FAILED",
    GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",

    GET_PURCHASES_WENT: "GET_PURCHASES_WENT",
    GET_PURCHASES_FAILED: "GET_PURCHASES_FAILED",
    GET_PURCHASES_REQUEST: "GET_PURCHASES_REQUEST",

    GET_DAILY_INFO_REQUEST: "GET_DAILY_INFO_REQUEST",
    GET_DAILY_INFO_WENT: "GET_DAILY_INFO_WENT",
    GET_DAILY_INFO_FAILED: "GET_DAILY_INFO_FAILED"
}